version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      new:
        aliases:
          - database
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      - database
    command: -source=file://migrations -database postgres://PG_USER:PG_PASS@database:5432/db?sslmode=disable up
    restart: on-failure
    networks:
      - new
    links:
      - database
  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - new
    ports:
      - "8080:5005"
volumes:
  data:
networks:
  new: