definitions:
  http_model.Transaction:
    properties:
      amount:
        type: number
      created_at:
        type: string
    type: object
  repo.Transaction:
    properties:
      amount:
        type: number
      created_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/health:
    get:
      consumes:
      - application/json
      description: Get health status.
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: get health status or 500
      tags:
      - Health
  /v1/transaction:
    get:
      consumes:
      - application/json
      description: Create transaction.
      parameters:
      - description: Start Time
        in: query
        name: start_time
        required: true
        type: string
      - description: End Time
        in: query
        name: end_time
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repo.Transaction'
      security:
      - ApiKeyAuth: []
      summary: create transaction
      tags:
      - Transaction
    post:
      consumes:
      - application/json
      description: Create transaction.
      parameters:
      - description: Transaction
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/http_model.Transaction'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repo.Transaction'
      security:
      - ApiKeyAuth: []
      summary: create transaction
      tags:
      - Transaction
swagger: "2.0"
